sspring.application.name=heart_link_backend

# Server
server.port=8080

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-plain-resonance-aytgw32m-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YdJVIcCT69WE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Brevo
brevo.api.key=${BREVO_API_KEY}